encoding: utf-8

# seo
title:Bo'bie
description: 
keywords:Bo'bie,PHP,HTML5,JavaScript,Js
author: Bo'bie

# "","/blog"
context: ""
"siteMapPrefix": "t"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2018晋ICP备16011602号
record: ""

coderay:
  coderay_tab_width: 4