encoding: utf-8

# seo
title:Berbie
description: 
keywords:Berbie,PHP,HTML5,JavaScript,Js
author: Berbie

# "","/blog"
context: ""
"siteMapPrefix": "http://www.wjinbo.com"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2018
record: "晋ICP备16011602号"

coderay:
  coderay_tab_width: 4