encoding: utf-8

# seo
title:
description: 
keywords: 
author: 

# "","/blog"
context: ""
"siteMapPrefix": "t"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2018
record: ""

coderay:
  coderay_tab_width: 4